FROM golang:1.20

# 设定时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 替换为国内的镜像源
RUN echo "deb http://mirrors.aliyun.com/debian/ bookworm main contrib non-free" | tee -a /etc/apt/sources.list
RUN echo "deb-src http://mirrors.aliyun.com/debian/ bookworm main contrib non-free" | tee -a /etc/apt/sources.list
RUN apt update

RUN apt-get install -y sudo curl gnupg

# #安装node官方源
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

# 安装 Node.js
RUN apt-get install -y nodejs

# 设置淘宝镜像源
RUN npm config set registry https://registry.npmmirror.com

# 更新npm
RUN npm install -g npm

# 安装upx
RUN sudo apt install -y upx-ucl

# 安装go-task
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/bin
